import Foundation
import Testing
@testable import CoreState

/// Strict v1 compatibility fixtures generated by the host's production wire
/// encoder. Normal test runs are read-only and compare exact bytes. Updating
/// the checked-in contract requires an explicit writer invocation:
///
///     xcodebuild test ... SWIFT_ACTIVE_COMPILATION_CONDITIONS='$(inherited) TOASTTY_WRITE_REMOTE_PROTOCOL_FIXTURES'
///
/// Review every resulting fixture diff before committing it.
struct RemoteProtocolGoldenTests {
    private static let fixtureDirectory = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("Tests/RemoteProtocol/Fixtures/v1", isDirectory: true)

    @Test func strictV1FixturesMatchHostEncoderBytes() throws {
        let fixtures = try Self.makeFixtures()
#if TOASTTY_WRITE_REMOTE_PROTOCOL_FIXTURES
        try FileManager.default.createDirectory(
            at: Self.fixtureDirectory,
            withIntermediateDirectories: true
        )
        for fixture in fixtures {
            try fixture.data.write(to: Self.fixtureDirectory.appendingPathComponent(fixture.name), options: .atomic)
        }
#endif

        let expectedNames = try Set(FileManager.default.contentsOfDirectory(
            at: Self.fixtureDirectory,
            includingPropertiesForKeys: nil
        ).map(\.lastPathComponent))
        #expect(expectedNames == Set(fixtures.map(\.name)), "Fixture files must exactly match the registered v1 contract")

        for fixture in fixtures {
            let expected = try Data(contentsOf: Self.fixtureDirectory.appendingPathComponent(fixture.name))
            #expect(fixture.data == expected, "Wire bytes changed for \(fixture.name); regenerate explicitly and review the diff")
        }
    }
}

private extension RemoteProtocolGoldenTests {
    struct Fixture {
        var name: String
        var data: Data
    }

    static let conversationID = RemoteConversationID(
        rawValue: UUID(uuidString: "11111111-1111-1111-1111-111111111111")!
    )
    static let projectionRunID = RemoteProjectionRunID(
        rawValue: UUID(uuidString: "22222222-2222-2222-2222-222222222222")!
    )
    static let bindingID = UUID(uuidString: "33333333-3333-3333-3333-333333333333")!
    static let workspaceID = UUID(uuidString: "44444444-4444-4444-4444-444444444444")!
    static let panelID = UUID(uuidString: "55555555-5555-5555-5555-555555555555")!
    static let deviceID = UUID(uuidString: "66666666-6666-6666-6666-666666666666")!
    static let timestamp = Date(timeIntervalSince1970: 1_786_200_000.125)

    static func makeFixtures() throws -> [Fixture] {
        let sessionSnapshot = makeSessionSnapshot()
        let eventPage = makeEventPage()
        let epoch = RemoteInputEpoch(bindingID: bindingID, counter: 42)

        var fixtures: [Fixture] = [
            try fixture("hello-response.json", RemoteGatewayHelloResponse()),
            try fixture(
                "pair-request.json",
                RemoteGatewayPairRequest(code: "ABCD-EFGH", deviceName: "Vishal's iPhone")
            ),
            try fixture(
                "pair-response.json",
                RemoteGatewayPairResponse(device: RemoteGatewayDeviceSummary(device: RemoteDeviceRecord(
                    id: deviceID,
                    name: "Vishal's iPhone",
                    scopes: [.approve, .read, .send],
                    createdAt: timestamp
                )))
            ),
            try fixture(
                "error-response.json",
                RemoteGatewayErrorResponse(code: "invalid_code", message: "Invalid or expired pairing code")
            ),
            try fixture("session-list-response.json", RemoteGatewaySessionListResponse(snapshot: sessionSnapshot)),
            try fixture(
                "events-request.json",
                RemoteGatewayEventsRequest(
                    conversationID: conversationID,
                    cursor: ConversationEventCursor(
                        projectionRunID: projectionRunID,
                        projectionGeneration: 7,
                        afterSequence: 12
                    ),
                    limit: 200
                )
            ),
            try fixture("events-response-page.json", RemoteGatewayEventsResponse.page(eventPage)),
            try fixture("events-response-resnapshot-required.json", RemoteGatewayEventsResponse.resnapshotRequired),
            try fixture("events-response-not-found.json", RemoteGatewayEventsResponse.conversationNotFound),
            try fixture("stream-session-list.json", RemoteGatewayStreamMessage.sessionList(sessionSnapshot)),
            try fixture("stream-conversation-events.json", RemoteGatewayStreamMessage.conversationEvents(eventPage)),
            try fixture(
                "stream-resnapshot-required.json",
                RemoteGatewayStreamMessage.resnapshotRequired(conversationID: conversationID)
            ),
            try fixture(
                "send-request.json",
                RemoteMessageSendRequest(
                    conversationID: conversationID,
                    clientRequestID: "ios-request-0001",
                    expectedInputEpoch: epoch,
                    text: "Please run the focused tests."
                )
            ),
            try fixture("send-result-accepted.json", RemoteMessageSendResult.accepted(epoch: epoch)),
            try fixture("send-result-uncertain.json", RemoteMessageSendResult.uncertain),
            try fixture("send-result-duplicate.json", RemoteMessageSendResult.duplicate),
        ]

        let rejectionReasons: [RemoteMessageRejectionReason] = [
            .sendScopeDenied,
            .sessionWritesDisabled,
            .notBound,
            .surfaceUnavailable,
            .promptNotOpen,
            .epochMismatch,
            .localDraftPresent,
            .pendingInteraction,
            .emptyText,
        ]
        fixtures += try rejectionReasons.map { reason in
            try fixture(
                "send-result-rejected-\(reason.rawValue).json",
                RemoteMessageSendResult.rejected(reason: reason)
            )
        }

        return fixtures
    }

    static func fixture<Value: Encodable>(_ name: String, _ value: Value) throws -> Fixture {
        Fixture(name: name, data: try ConversationEventCoding.makeEncoder().encode(value))
    }

    static func makeSessionSnapshot() -> RemoteSessionListSnapshot {
        let states: [RemoteSessionState] = [
            .starting,
            .working,
            .awaitingInput,
            .ready,
            .interrupted,
            .ended,
            .error,
            .offline,
            .awaitingInput,
            .awaitingInput,
            .awaitingInput,
        ]
        let inputAvailability: [RemoteInputAvailability] = [
            .unavailable(reason: .starting),
            .unavailable(reason: .working),
            .unavailable(reason: .interrupted),
            .unavailable(reason: .ended),
            .unavailable(reason: .error),
            .unavailable(reason: .offline),
            .unavailable(reason: .surfaceUnavailable),
            .unavailable(reason: .unknownProviderState),
            .openPrompt(epoch: RemoteInputEpoch(bindingID: bindingID, counter: 8)),
            .pendingInteraction(interactionIDs: [
                RemotePendingInteraction.ID(rawValue: "codex:approval:pending-1"),
                RemotePendingInteraction.ID(rawValue: "claude:question:pending-2"),
            ]),
            .localDraft(epoch: RemoteInputEpoch(bindingID: bindingID, counter: 9)),
        ]
        let providers: [AgentKind] = [.codex, .claude, .opencode, .mimocode, .pi, .processWatch]

        let conversations = zip(states, inputAvailability).enumerated().map { index, pair in
            let (state, availability) = pair
            let number = index + 1
            return RemoteConversationSummary(
                conversationID: RemoteConversationID(rawValue: numberedUUID(number)),
                provider: providers[index % providers.count],
                title: "Conversation \(number): \(state.rawValue)",
                placement: index.isMultiple(of: 2)
                    ? RemoteConversationPlacement(
                        workspaceID: workspaceID,
                        workspaceTitle: "Mobile Remote Access",
                        panelID: panelID
                    )
                    : RemoteConversationPlacement(),
                cwd: index.isMultiple(of: 2) ? "/Users/example/Toastty" : nil,
                state: state,
                inputAvailability: availability,
                projectionGeneration: UInt64(index),
                latestSequence: UInt64(index * 10),
                updatedAt: timestamp.addingTimeInterval(Double(index))
            )
        }

        return RemoteSessionListSnapshot(
            projectionRunID: projectionRunID,
            conversations: conversations,
            generatedAt: timestamp.addingTimeInterval(60)
        )
    }

    static func makeEventPage() -> ConversationEventPage {
        var events: [ConversationEvent] = []

        for (origin, requestID) in [
            (ConversationMessageOrigin.local, nil),
            (.remote, "ios-request-0001"),
            (.unknown, nil),
        ] {
            appendEvent(
                to: &events,
                payload: .userMessage(ConversationUserMessagePayload(
                    text: "User message from \(origin.rawValue)",
                    origin: origin,
                    clientRequestID: requestID
                ))
            )
        }

        for phase in [
            ConversationAssistantMessagePhase.commentary,
            .final,
            .unknown,
        ] {
            appendEvent(
                to: &events,
                payload: .assistantMessage(ConversationAssistantMessagePayload(
                    text: "Assistant \(phase.rawValue)",
                    phase: phase
                ))
            )
        }

        appendEvent(
            to: &events,
            payload: .toolStarted(ConversationToolStartedPayload(
                callID: "call-start-detailed",
                toolName: "exec_command",
                detail: "swift test --filter Remote"
            ))
        )
        appendEvent(
            to: &events,
            payload: .toolStarted(ConversationToolStartedPayload(
                callID: "call-start-minimal",
                toolName: "read_file"
            ))
        )

        for outcome in [ConversationToolOutcome.succeeded, .failed, .unknown] {
            appendEvent(
                to: &events,
                payload: .toolFinished(ConversationToolFinishedPayload(
                    callID: "call-finished-\(outcome.rawValue)",
                    toolName: outcome == .unknown ? nil : "exec_command",
                    outcome: outcome,
                    detail: outcome == .succeeded ? "Passed" : nil
                ))
            )
        }

        let statusStates: [RemoteSessionState] = [
            .starting, .working, .awaitingInput, .ready, .interrupted, .ended,
            .error, .offline, .awaitingInput, .awaitingInput, .awaitingInput,
        ]
        let statusAvailability: [RemoteInputAvailability] = [
            .unavailable(reason: .starting),
            .unavailable(reason: .working),
            .unavailable(reason: .interrupted),
            .unavailable(reason: .ended),
            .unavailable(reason: .error),
            .unavailable(reason: .offline),
            .unavailable(reason: .surfaceUnavailable),
            .unavailable(reason: .unknownProviderState),
            .openPrompt(epoch: RemoteInputEpoch(bindingID: bindingID, counter: 20)),
            .pendingInteraction(interactionIDs: [RemotePendingInteraction.ID(rawValue: "codex:approval:event")]),
            .localDraft(epoch: RemoteInputEpoch(bindingID: bindingID, counter: 21)),
        ]
        for (state, availability) in zip(statusStates, statusAvailability) {
            appendEvent(
                to: &events,
                payload: .statusChanged(ConversationStatusChangedPayload(
                    state: state,
                    inputAvailability: availability
                ))
            )
        }

        for (index, kind) in [
            RemotePendingInteraction.Kind.permission,
            .question,
            .structuredChoice,
            .freeForm,
        ].enumerated() {
            let state: RemotePendingInteraction.State = switch index {
            case 0: .pending
            case 1: .resolved
            default: .superseded
            }
            appendEvent(
                to: &events,
                payload: .interactionPresented(RemotePendingInteraction(
                    id: RemotePendingInteraction.ID(rawValue: "interaction-\(kind.rawValue)"),
                    kind: kind,
                    providerCallID: index.isMultiple(of: 2) ? "provider-call-\(index)" : nil,
                    providerApprovalID: index.isMultiple(of: 2) ? nil : "approval-\(index)",
                    prompt: "Respond to \(kind.rawValue)",
                    options: [
                        RemotePendingInteraction.Option(id: "allow", label: "Allow", detail: "Proceed once"),
                        RemotePendingInteraction.Option(id: "deny", label: "Deny"),
                    ],
                    inputEpoch: RemoteInputEpoch(bindingID: bindingID, counter: UInt64(30 + index)),
                    presentedAt: timestamp.addingTimeInterval(Double(index)),
                    state: state
                ))
            )
        }

        for state in [
            RemotePendingInteraction.State.pending,
            .resolved,
            .superseded,
        ] {
            appendEvent(
                to: &events,
                payload: .interactionResolved(ConversationInteractionResolvedPayload(
                    interactionID: RemotePendingInteraction.ID(rawValue: "resolved-\(state.rawValue)"),
                    resolution: state
                ))
            )
        }

        for phase in [
            ConversationSubagentPhase.started,
            .updated,
            .finished,
            .unknown,
        ] {
            appendEvent(
                to: &events,
                payload: .subagentSummary(ConversationSubagentSummaryPayload(
                    subagentID: "subagent-\(phase.rawValue)",
                    displayName: "Protocol \(phase.rawValue)",
                    phase: phase,
                    detail: phase == .unknown ? nil : "Fixture detail"
                ))
            )
        }

        for reason in [
            ConversationBindingChangeReason.runtimeBound,
            .runtimeResumed,
            .runtimeEnded,
            .projectionRebuilt,
        ] {
            appendEvent(
                to: &events,
                payload: .sessionBindingChanged(ConversationSessionBindingChangedPayload(
                    reason: reason,
                    providerSessionID: reason == .runtimeEnded ? nil : "provider-session-\(reason.rawValue)",
                    providerSessionFilePath: reason == .runtimeEnded ? nil : "/tmp/\(reason.rawValue).jsonl"
                ))
            )
        }

        return ConversationEventPage(
            conversationID: conversationID,
            projectionRunID: projectionRunID,
            projectionGeneration: 7,
            events: events,
            latestSequence: UInt64(events.count + 8),
            firstAvailableSequence: 3,
            historyTruncated: true
        )
    }

    static func appendEvent(to events: inout [ConversationEvent], payload: ConversationEventPayload) {
        let sequence = UInt64(events.count + 1)
        let providers: [AgentKind] = [.codex, .claude, .opencode, .mimocode, .pi]
        events.append(ConversationEvent(
            conversationID: conversationID,
            sequence: sequence,
            eventID: "fixture:event:\(sequence)",
            timestamp: timestamp.addingTimeInterval(Double(sequence) / 10),
            provider: providers[events.count % providers.count],
            providerIdentity: events.count.isMultiple(of: 2) ? "provider-id-\(sequence)" : nil,
            turnID: events.count.isMultiple(of: 3) ? "turn-\(sequence)" : nil,
            payload: payload
        ))
    }

    static func numberedUUID(_ number: Int) -> UUID {
        UUID(uuidString: String(format: "00000000-0000-0000-0000-%012d", number))!
    }
}
