/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.relay.jsonc --env=test --include-runtime=false --strict-vars=false --env-interface=RelayEnv relay-configuration.d.ts` (hash: e31efda94b2eba31f95b625262588918)
interface __BaseEnv_RelayEnv {
	PUSH_ENABLED: string;
	PUSH_RELAY_ID: string;
	APNS_ENVIRONMENT: string;
	APNS_TOPIC: string;
	APNS_PRIVATE_KEY: string;
	APNS_KEY_ID: string;
	APNS_TEAM_ID: string;
	PUSH_STATE: DurableObjectNamespace<import("./src/relay").PushRelayState>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/relay");
		durableNamespaces: "PushRelayState";
	}
	interface Env extends __BaseEnv_RelayEnv {}
}
interface RelayEnv extends __BaseEnv_RelayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUSH_ENABLED" | "PUSH_RELAY_ID" | "APNS_ENVIRONMENT" | "APNS_TOPIC" | "APNS_PRIVATE_KEY" | "APNS_KEY_ID" | "APNS_TEAM_ID">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}